// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2vqdLAU36A4Y7gXBQryRRS9nAzjMs7nw',
    appId: '1:513243809201:web:36135064b854bddfc36990',
    messagingSenderId: '513243809201',
    projectId: 'urbanrider-2109c',
    authDomain: 'urbanrider-2109c.firebaseapp.com',
    storageBucket: 'urbanrider-2109c.appspot.com',
    measurementId: 'G-BGZV8PR4NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA27V4WmtSZvRwF1QXeSqV8DtlZJCoy0RY',
    appId: '1:513243809201:android:6d3af712ec898629c36990',
    messagingSenderId: '513243809201',
    projectId: 'urbanrider-2109c',
    storageBucket: 'urbanrider-2109c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS778xgELFy4MesTTmSSbX7Vf_D_sNxGg',
    appId: '1:513243809201:ios:1036df4cd40b4fe0c36990',
    messagingSenderId: '513243809201',
    projectId: 'urbanrider-2109c',
    storageBucket: 'urbanrider-2109c.appspot.com',
    iosBundleId: 'com.example.urbanRiders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS778xgELFy4MesTTmSSbX7Vf_D_sNxGg',
    appId: '1:513243809201:ios:0fb6da240e85d5b5c36990',
    messagingSenderId: '513243809201',
    projectId: 'urbanrider-2109c',
    storageBucket: 'urbanrider-2109c.appspot.com',
    iosBundleId: 'com.example.urbanRiders.RunnerTests',
  );
}
